### PR TITLE
fix: subscription type static typings

### LINKED ISSUE #559: subscription block t-helpers missing "subscribe" field typing
For example, in the following, `t.field` works but `t.boolean` does not––it "thinks" `subscribe` is an invalid field.

image

### PR DESCRIPTION
**Pull request by jasonkuhrt**
fixes #559

This takes another stab at implementing subscription type. It fixes multiple things.

- It no longer sub-classes from Object Type. This means we lose interface implements support. However this was never tested before and it is unclear its even a feature we want.
- It simplifies the field shorthand typings by removing the resolver shorthand param style. This style is unusable since subscribe config field is always needed anyways.
- It fixes field shorthand config which would fail when typegen was present. Specifically the subscribe field was not being recognized before.

Also

- It adds subscription type test cases to integration test. This way we capture the error that only happens when typegen is present.

### CODE REVIEW

File: tests/integration/_app.ts [hunk 1]
```diff
@@ -96,3 +98,76 @@ export const Mutation = mutationType({
     })
   },
 })
+
+export const Subscription = subscriptionType({
```
Comment (jasonkuhrt) [inline tests/integration/_app.ts:102]: Now we cover subscription type in integration tests.

File: src/definitions/subscriptionType.ts [hunk 2]
```diff
@@ -66,66 +17,92 @@ export interface SubscribeFieldConfig<TypeName extends string, FieldName extends
...
+export interface SubscribeFieldConfig<TypeName extends string, FieldName extends string>
+  extends SubscribeFieldConfigBase<FieldName>,
+          CommonOutputFieldConfig<'Subscription', FieldName>
+  {
+    type: GetGen<'allOutputTypes'> | AllNexusOutputTypeDefs
   }
 
+export interface SubscriptionBuilderInternal extends ObjectDefinitionBuilder<'Subscription'> {}
+
+export class SubscriptionBuilder {
```
Comment (jasonkuhrt) [inline src/definitions/subscriptionType.ts:41]: No more subclassing `ObjectDefinitionBuilder`

File: src/definitions/subscriptionType.ts [hunk 3]
```diff
@@ -66,66 +17,92 @@ export interface SubscribeFieldConfig<TypeName extends string, FieldName extends
...
+
   get list() {
     if (this.isList) {
       throw new Error('Cannot chain list.list, in the definition block. Use `list: []` config value')
     }
-    return new SubscriptionDefinitionBlock(this.typeBuilder, true)
+    return new SubscriptionBuilder(this.typeBuilder, true)
+  }
+
+  string<FieldName extends string>(fieldName: FieldName, config: FieldShorthandConfig<FieldName>) {
```
Comment (jasonkuhrt) [inline src/definitions/subscriptionType.ts:51]: No more spread confusion needed, as config will _always_ be needed.

File: src/definitions/subscriptionType.ts [hunk 4]
```diff
@@ -66,66 +17,92 @@ export interface SubscribeFieldConfig<TypeName extends string, FieldName extends
...
-    ...opts: ScalarSubSpread<'Subscription', FieldName>
-  ) {
-    this.addScalarField(fieldName, 'String', opts)
+  int<FieldName extends string>(fieldName: FieldName, config: FieldShorthandConfig<FieldName>) {
+    this.fieldShorthand(fieldName, 'Int', config)
   }
 
-  int<FieldName extends string>(fieldName: FieldName, ...opts: ScalarSubSpread<'Subscription', FieldName>) {
-    this.addScalarField(fieldName, 'Int', opts)
+  // prettier-ignore
```
Comment (jasonkuhrt) [inline src/definitions/subscriptionType.ts:59]: Much easier to read these signatures as one-liners.

File: src/definitions/subscriptionType.ts [hunk 5]
```diff
@@ -66,66 +17,92 @@ export interface SubscribeFieldConfig<TypeName extends string, FieldName extends
 
   subscribe(
     root: object,
-    args: ArgsValue<TypeName, FieldName>,
+    args: ArgsValue<'Subscription', FieldName>,
```
Comment (jasonkuhrt) [inline src/definitions/subscriptionType.ts:20]: Hardcoding instead of needless indirection.

File: src/definitions/subscriptionType.ts [hunk 6]
```diff
@@ -1,63 +1,14 @@
...
-  type: GetGen<'allOutputTypes'> | AllNexusOutputTypeDefs
-
-  /**
-   * Resolve method for the field
-   */
+export interface SubscribeFieldConfigBase<FieldName extends string, Event = any> {
   resolve(
-    root: T,
-    args: ArgsValue<TypeName, FieldName>,
+    root: Event,
```
Comment (jasonkuhrt) [inline src/definitions/subscriptionType.ts:10]: We have some feature work to do to make this typesafe in practice for users.

File: src/definitions/subscriptionField.ts [hunk 7]
```diff
@@ -14,7 +14,7 @@ export function subscriptionField<FieldName extends string>(
     type: 'Subscription',
     definition(t) {
       const finalConfig = typeof config === 'function' ? config() : config
-      t.field(fieldName, finalConfig)
+      t.field(fieldName, finalConfig as any)
```
Comment (jasonkuhrt) [inline src/definitions/subscriptionField.ts:17]: Gets us around this issue for now:

image

Comment (jasonkuhrt) [reply src/definitions/subscriptionField.ts:17]: Maybe we should try to fix now.

File: src/definitions/definitionBlocks.ts [hunk 8]
```diff
@@ -158,8 +154,7 @@ export class OutputDefinitionBlock<TypeName extends string> {
     // 2. NexusOutputFieldDef is contrained to be be a string
     // 3. so `name` is not compatible
     // 4. and changing FieldOutConfig to FieldOutConfig<string breaks types in other places
-    const field: any = { name, ...fieldConfig }
```
Comment (jasonkuhrt) [inline src/definitions/definitionBlocks.ts:161]: Pretty confusing identifier name.

File: src/definitions/definitionBlocks.ts [hunk 9]
```diff
@@ -64,28 +64,24 @@ export type NexusOutputFieldDef = NexusOutputFieldConfig<string, any> & {
...
-
-export type ScalarOutConfig<TypeName extends string, FieldName extends string> = NeedsResolver<
-  TypeName,
-  FieldName
-> extends true
-  ? OutputScalarConfig<TypeName, FieldName> & {
-      resolve: FieldResolver<TypeName, FieldName>
-    }
-  : OutputScalarConfig<TypeName, FieldName>
+// prettier-ignore
```
Comment (jasonkuhrt) [inline src/definitions/definitionBlocks.ts:67]: Formatting improvements.

Comment (jasonkuhrt) [reply src/definitions/definitionBlocks.ts:67]: This was after I had made actual logical changes, then undid them. Didn't revert everything as the new formatting seemed better.

File: src/definitions/subscriptionType.ts (hunk 6 above)
Comment (Weakky) [reply src/definitions/subscriptionType.ts:10]: Isn't it typesafe already?

**Comment by Weakky** [comment]
> It no longer sub-classes from Object Type. This means we lose interface implements support. However, this was never tested before and it is unclear it's even a feature we want.

Technically, it doesn't seem something that 99% of use-cases will need, so I'd be fine rolling this out until someone yells.

However, while this will require slightly more work, I don't see reasons why we could not add GraphQL interface inheritance support even if the internal subscription class no longer "super-classes" the object type one. That's really just an implementation detail.

@tgriesser WDYT?

File: src/definitions/subscriptionType.ts (hunk 6 above)
Comment (jasonkuhrt) [reply src/definitions/subscriptionType.ts:10]: No, the resolve `root` type should match the type returned from `subscribe`.

https://github.com/graphql-nexus/schema/issues/454

File: src/definitions/subscriptionField.ts (hunk 7 above)
Comment (jasonkuhrt) [reply src/definitions/subscriptionField.ts:17]: Found a fix, solution was to make `extendType` builder API polymorphic over the value of `TypeName`. Specifically branching over if it is `Subscription` or not.

File: src/definitions/extendType.ts [hunk 10]
```diff
@@ -1,11 +1,14 @@
...
 import { AllOutputTypesPossible } from '../typegenTypeHelpers'
 import { OutputDefinitionBlock } from './definitionBlocks'
+import { IsSubscriptionType, SubscriptionBuilder } from './subscriptionType'
 import { NexusTypes, withNexusSymbol } from './_types'
 
 export interface NexusExtendTypeConfig<TypeName extends string> {
   type: TypeName
-  definition(t: OutputDefinitionBlock<TypeName>): void
+  definition(
+    t: IsSubscriptionType<TypeName> extends true ? SubscriptionBuilder : OutputDefinitionBlock<TypeName>
```
Comment (jasonkuhrt) [inline src/definitions/extendType.ts:10]: Make `extendType` builder API polymorphic over the value of `TypeName`. Specifically branching over if it is `Subscription` or not. This is needed since the types are different. The naming is a new problem now. That is, `OutputDefinitionBlock` should be called something else. Or, it should be refactored to still fulfill the role of generic handling of `Output`.

File: src/definitions/subscriptionType.ts (hunk 6 above)
Comment (Weakky) [reply src/definitions/subscriptionType.ts:11]: Yeah but the `Event` generic already does that, although it seems it's not properly captured as explained by that issue 👍

**Comment by jasonkuhrt** [comment]
I think this is good enough to not keep blocking the fix from being released.
